### PR TITLE
 BasicMath Pull Request Into Official

### PR DESCRIPTION
**Pull request by 42null**
This is my extension that I have been working on. It is a extension that allows SEPIA to do math. More information is available on https://github.com/42null/42null-SEPIA-Extensions.

### CODE REVIEW

**Comment by fquirin** [comment]
Hi 42null,
thanks for this contribution! 
I somehow missed the notification for the pull request but will check it out immediately! :smiley:

**Comment by 42null** [comment]
No problem, I get it, I am quite swamped right now as well. I hope that I didn't make the comments too hard to read.

-Enjoy the rest of your day!
      42null  :)

**Comment by fquirin** [comment]
Hi 42null,

after what feels like a little lifetime I finally released SEPIA v2.5.1 and then took a look at your BasicMath service :slightly_smiling_face: 

First of all let me say that I really appreciate how much work you obviously put into this and the result looks very promising! I'd be very happy to see some follow-up work on it :sunglasses: :+1:.
There are several aspects I'll probably carry over to the other SDK services like the versioning approach for example and its interesting to see how you push the SDK and NLU processor to its limits :grin: 

That said there are a few aspects I'd like to discuss before accepting the pull request.

### 1. General structure of the service

The SEPIA chain of events is roughly as follows:
- normalize user input
- check if we can identify user intent
- if we found a possible matching intent get the related service and the set of required and optional parameters
- use the `extract` method of all given parameters to see if we can find the parameter inside the user input
- score the possible intent and if it has the best score use the `build` function for every parameter that was extracted
- send everything to the service `getResult` method for actual service tasks

Now looking at your service you are using a single parameter **GetFirstNumber** and this parameter is basically doing all calculations of the service in it's **extract** phase. For the chain of events above this means that all the heavy lifting is done in a phase where SEPIA is actually still calculating if the service will be used at all. This will slow down processing quite a bit.  
  
I'd propose the following changes:
- Rename `GetFirstNumber` to `GetCalculationFormula` (or something similar)
- Use the `extract` method only to check if we have anything that looks like a formula
- Use the `build` method of the parameter to do some processing of the formula (optional) and maybe use the raw input (non-normalized user input) `String rawInput = this.nluInput.textRaw;` if your formula got screwed up by input normalization ^^
- Do all actual calculations inside the `getResult` method and make use of 'success' (calculation was possible and got result), 'okay' (calculation not possible, maybe not correct formula or instruction) and 'fail' (something actually crashed the calculation)

### 2. Mentioned bugs

You mention a couple of bugs that you couldn't fix from your side. I took a look at a few of them, e.g.:
- `3.) /0 ...` - is happening inside your `orderOfOperations()` method. You can catch that error by putting a `try { ... } catch ...` around the code in your `extract` method.
- `4.) n1"teen" (e.g. thirteen) ...` - is working just fine for me :thinking: (maybe I didn't get the point here)

I didn't test all of them but I'd suggest to use the `TestServiceLocally` class of the SDK to run controlled tests of your parameter extraction and build methods and the service `getResult` method. In the latest SDK Update I've further improved the available test methods (currently in SDK dev-branch, supports SEPIA-Home v2.5.1, will be merged into master this week).

### 3. Other things I've noticed

- "x" ist often used by ASR or users instead of "times" or "✕" which might be problematic in your parsing method
- `whatis` should not be used inside your regular expressions since it is too general to be connected to this service only. `calculate` is perfectly fine though :slightly_smiling_face: 
- There are quite a few spelling mistakes in your code comments and some issues with indentation, I've tried to clean up a bit and appended the updated file here (feel free to use it or ignore it ^^): [BasicMath.zip](https://github.com/SEPIA-Framework/sepia-extensions/files/5429355/BasicMath.zip)

I hope you'll find the time to read this and continue to work on the service, I'd love to include it in the extensions repository of SEPIA :smiley: 

Regards,
Florian

**Comment by 42null** [comment]
Thank you so much for your reply Florian, I will be closely reading your feedback and I am planning that one day I will have the expertise to finish this. When I started the BasicMath project I bit off more then I could chew as someone who's java programming experience did not contain any smart-service structure knowledge. I should not have pushed so hard to just get something somewhat functional, but something I was not entirely proud of, out onto the project. I submitted it just so I would not feel obligated to spend any more time being frustrated over the program which clearly was a mistake. Right now I am taking an extended break from that file and will spend more time getting to know the process on which this great voice assistant program is based on instead of just guessing and checking until something works. Right now I actually am in the middle of working on another extension that I feel is much better suited for my skill level and that I can use to get better. For now I am keeping it unreleased but if I get it to a level I am proud of, and of much higher quality, I might submit another pull request. I hope that the experience gained from completing it will allow me to grow as a programmer and I will be looking though what you have written for learning material as well.

I can't thank you enough for your analysis and I appreciate it greatly. I can't wait to see what the future of the SEPIA project holds. Please enjoy the rest of your day,
      -42null

**Comment by fquirin** [comment]
Thanks a lot for your kind words and for actually trying to work through this :smiley: , I know the documentation isn't great (yet) :sweat_smile: and I think its pretty cool that you came this far already! Take your time and see you around :+1:

**Pull request closed without merging**
